# Generated by Django 5.0.7 on 2024-08-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_takenbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['title']},
        ),
    ]
