# Generated by Django 5.0.7 on 2024-08-07 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenbooks',
            name='taken_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
